---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 導入後は、すべてのネットアップストレージコンポーネントをアップグレードすることで、 SolidFire Element ストレージシステムを最新の状態に保つことができます。 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= アップグレード手順の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入後も SolidFire Element ストレージシステムを最新の状態に保つには、すべてのネットアップストレージコンポーネントを順番にアップグレードします。

これらのコンポーネントには、管理サービス、NetApp Hybrid Cloud Control、Elementソフトウェア、管理ノード、および（インストール環境に応じて）Element Plug-in for vCenter Serverが含まれます。

[NOTE]
====
* 2023年11月以降、署名キー証明書（プライベートおよびパブリック）の有効期限が2023年11月5日に切れたため、NetApp Hybrid Cloud ControlまたはREST APIを使用してコンポーネントのアップグレードを開始することはできません。この問題を解決するには、Knowledge Baseの記事に記載されている回避策を実行し https://kb.netapp.com/onprem/solidfire/Element_OS/SolidFire_and_HCI_upgrades_unable_to_start_due_to_upgrade_package_upload_error["アップグレードパッケージのアップロードエラーが原因でSolidFireとHCIのアップグレードを開始できない"^]ます。
* Element 12.7以降では、SF2405およびSF9608ストレージノード、FC0025およびSF-FCN-01 FCノードはサポートされていません。これらのノードのいずれかをElement 12.7にアップグレードしようとすると、このノードがElement 12.7でサポートされていないことを示すエラーが表示されます。
* Element 12.5以降では、ElementソフトウェアのアップグレードでNetApp HealthToolsがサポートされなくなりました。Element 11.0または11.1を実行している場合は、NetAppハイブリッドクラウドコントロールを使用してElement 12.5以降にアップグレードする必要があります https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["HealthToolsを使用してElement 12.3にアップグレードします"^]。


====
この<<sys_upgrade,システムのアップグレード順序>>コンテンツでは、SolidFireオールフラッシュストレージシステムのアップグレードを完了するために必要なタスクについて説明します。これらの手順は、単独ででではなく、大きなアップグレード手順の一部として実行することを推奨します。コンポーネントベースのアップグレードまたは更新が必要な場合は、手順の前提条件を参照して、さらに複雑な作業が対処されるようにしてください。

「Element Plug-in for vCenter Serverを含む」のコンテンツでは、link:task_sf_upgrade_all_vsphere.html["vSphere のアップグレード順序"]Element Plug-in for vCenter Serverを再インストールするために必要なアップグレード前後の追加の手順について説明しています。

.必要なもの
* 管理ノード 11.3 以降が実行されていることを確認します。新しいバージョンの管理ノードには、個々のサービスを提供するモジュラアーキテクチャが採用されています。
+

TIP: バージョンを確認するには、管理ノードにログインし、ログインバナーに表示される Element のバージョン番号を確認します。11.3がインストールされていない場合は、を参照してくださいlink:task_hcc_upgrade_management_node.html["管理ノードをアップグレードします"]。

* 管理サービスをバージョン 2.1.326 以上にアップグレードしておきます。
+
NetApp Hybrid Cloud Control を使用したアップグレードは、それよりも前のバージョンのサービスバンドルでは利用できません。

* すべてのノードのシステム時間が同期され、 NTP がストレージクラスタとノードに対して正しく設定されていることを確認しておきます。各ノードで、ノードWeb UIでDNSネームサーバを設定する必要があり(`https://[IP address]:442`ます）。時刻のずれに関連する未解決のクラスタ障害が発生していないことを確認します。
* とのlink:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["ストレージファームウェア"]アップグレードに十分な時間をスケジュールしておきlink:task_hcc_upgrade_element_software.html#element-upgrade-time["Element ソフトウェア"]ます。Elementソフトウェア12.5以降にアップグレードする場合は、Elementソフトウェアのバージョンとファームウェアの更新によってアップグレードプロセスの時間が異なります。




== [[sys_upgrade]システムのアップグレード順序

Element 12.5以降では、次の順序でNetApp SolidFire オールフラッシュストレージシステムをアップグレードできます。

.手順
. link:task_hcc_update_management_services.html["Hybrid Cloud Control から管理サービスを更新します"]です。
+

IMPORTANT: 管理サービスをバージョン 2.16 以降に更新する場合、管理ノード 11.3 から 11.8 を実行しているときは、管理サービスを更新する前に管理ノード VM の RAM を増やす必要があります。

+

IMPORTANT: Element ソフトウェアをアップグレードする前に、最新の管理サービスバンドルに更新する必要があります。

. link:task_hcc_upgrade_element_prechecks.html["ストレージをアップグレードする前に、 Element ストレージの健全性チェックを実行します"]です。
. link:task_hcc_upgrade_element_software.html["Element ソフトウェアとストレージファームウェアをアップグレードします"]です。
. link:task_hcc_upgrade_storage_firmware.html["（オプション） Element ストレージファームウェアのみをアップグレードします"]です。
+

NOTE: このタスクは、メジャーリリース以外で新しいストレージファームウェアアップグレードがリリースされたときに実行することができます。

. link:task_hcc_upgrade_management_node.html["（オプション）管理ノードをアップグレードします"]です。
+

NOTE: ストレージクラスタ上の Element ソフトウェアをアップグレードするために、管理ノードのオペレーティングシステムをアップグレードする必要がなくなりました。管理ノードのバージョンが 11.3 以降である場合は、 NetApp Hybrid Cloud Control を使用して管理サービスを最新バージョンにアップグレードするだけで Element をアップグレードできます。管理ノードのオペレーティングシステムをアップグレードする理由がほかにもある場合は、セキュリティの修正など、管理ノードのアップグレード手順に従ってください。

. link:task_vcp_upgrade_plugin.html["Element Plug-in for vCenter Server をアップグレードします"]です。


[discrete]
== 詳細情報

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"]

