---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 著作権
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. All rights reserved.米国で印刷されています。

このドキュメントは著作権によって保護されています。著作権所有者の書面による事前承諾がある場合を除き、画像媒体、電子媒体、および写真複写、記録媒体、テープ媒体、電子検索システムへの組み込みを含む機械媒体など、いかなる形式および方法による複製も禁止します。

著作権で保護されたNetApp素材から派生したソフトウェアには、次の使用許諾および免責条項が適用されます。

このソフトウェアは、NetAppによって「現状のまま」提供されています。明示的な保証、または商品性および特定目的への適合性の暗示的保証を含み、かつこれに限定されないいかなる暗示的な保証も行いません。いかなる場合においても、NetAppは、直接的、間接的、偶発的、特別、明示的、または結果的な損害(代替商品またはサービスの調達、使用、データまたは利益の損失、またはビジネスの中断を含みますが、これらに限定されません)について、また、このようなソフトウェアの使用、使用、またはそのような責任の理論のいずれかにかかわらず、このような方法での損害を含め、責任を負わないものとします。

NetAppは、ここに記載されている製品をいつでも予告なく変更する権利を留保します。NetAppは、NetAppが書面で明示的に合意した場合を除き、ここに記載されている製品の使用に起因する責任または責任を負いません。この製品の使用または購入は、NetAppの特許権、商標権、またはその他の知的財産権に基づくライセンスを提供するものではありません。

このマニュアルに記載されている製品は、1つ以上の米国特許、その他の国の特許、および出願中の特許によって保護されている場合があります。

本書に含まれるデータは市販品（FAR 2.101の定義に基づく）に関係し、データの所有権はNetApp, Inc.にあります。米国政府は本データに対し、非独占的かつ移転およびサブライセンス不可で、全世界を対象とする取り消し不能の制限付き使用権を有し、本データの提供の根拠となった米国政府契約に関連し、当該契約の裏付けとする場合にのみ本データを使用できます。本契約に規定されている場合を除き、NetApp、Inc.の書面による事前の承認なしに、データを使用、開示、複製、改変、実行、または表示することはできません。国防総省に対する米国政府のライセンス権は、DFARS 252.227-7015（b）項で特定された権利に限定されます。
