---
permalink: api/reference_element_api_signsshkeys.html 
sidebar: sidebar 
keywords: ssh, sign key 
summary: ノードまたはクラスタでsshを有効にしたあと、SignSshKeysメソッドを使用して、sfadminまたはsfreadonlyとしてノード上のシェルにアクセスできます。sfreadonlyはElement 12.5以降の新しいユーザアカウントで、ノードでの初期トラブルシューティングは可能ですが、昇格されたコマンドを作成するためのPrivilegesはありません。 
---
= SigSshKeys
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用してクラスタでSSHを有効にするlink:../api/reference_element_api_enablessh.html["EnableSSHメソッド"]と、メソッドを使用してノードのシェルにアクセスできます `SignSshKeys`。

Element 12.5以降では、 `sfreadonly`新しいシステムアカウントでノードの基本的なトラブルシューティングを実行できます。このAPIを使用すると、クラスタ内のすべてのノードで、システムアカウントを使用したSSHアクセスが可能になり `sfreadonly`ます。


WARNING: ネットアップサポートから指示されないかぎり、システムに対する変更はサポートされず、サポート契約にも取り消しが含まれ、データが不安定になったり、アクセスできなくなる可能性があります。

メソッドを使用した後、応答からキーチェーンをコピーし、SSH接続を開始するシステムに保存してから、次のコマンドを実行する必要があります。

[listing]
----
ssh -i <identity_file> sfreadonly@<node_ip>
----
 `identity_file`は、公開鍵認証用のID（秘密鍵）の読み取り元のファイルで、はノードのIPアドレスです。 `node_ip`詳細については `identity_file`、SSHのマニュアルページを参照してください。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 製品説明 | タイプ | デフォルト値 | 必須 


 a| 
期間
 a| 
符号付きキーが有効である時間数を示す1～24の整数。durationを指定しなかった場合は、デフォルト値が使用されます。
 a| 
整数
 a| 
1
 a| 
いいえ



 a| 
publickey
 a| 
このパラメータを指定すると、ユーザに完全なキーチェーンを作成するのではなく、signed_public_keyのみが返されます。


NOTE: を使用してブラウザでURLバーを使用して送信された公開鍵 `+`は、スペース署名およびブレーク署名として解釈されます。
 a| 
文字列
 a| 
ヌル
 a| 
いいえ



 a| 
sfadmin
 a| 
supportAdminクラスタアクセスを使用してAPI呼び出しを行う場合、またはノードがクラスタにない場合に、sfadminシェルアカウントへのアクセスを許可します。
 a| 
ブーリアン
 a| 
正しくない
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 製品説明 | タイプ 


 a| 
keygen_statusのように入力します
 a| 
署名付きキーのID、許可されているプリンシパル、およびキーの有効な開始日と終了日が含まれます。
 a| 
文字列



 a| 
private_key を使用します
 a| 
プライベートSSHキーの値は、APIがエンドユーザの完全なキーチェーンを生成している場合にのみ返されます。


NOTE: 値はBase64でエンコードされます。値がファイルに書き込まれるときに値をデコードして、有効な秘密鍵として読み取られるようにする必要があります。
 a| 
文字列



 a| 
公開鍵
 a| 
公開SSHキーの値は、APIがエンドユーザの完全なキーチェーンを生成している場合にのみ返されます。


NOTE: APIメソッドにpublic_keyパラメータを渡した場合、応答では値のみが `signed_public_key`返されます。
 a| 
文字列



 a| 
signed_public_key
 a| 
ユーザが指定したか生成したかに関係なく、公開鍵への署名で生成されたSSH公開鍵。
 a| 
文字列

|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
    "method": "SignSshKeys",
    "params": {
        "duration": 2,
        "publicKey":<string>
    },
    "id": 1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": null,
  "result": {
    "signedKeys": {
      "keygen_status": <keygen_status>,
      "signed_public_key": <signed_public_key>
    }
  }
}
----
この例では、期間（1～24時間）に有効な公開鍵が署名され、返されます。



== 新規導入バージョン

12.5
