---
permalink: api/reference_element_api_ldapconfiguration.html 
sidebar: sidebar 
keywords: object,objects,ldapConfiguration 
summary: ldapConfiguration オブジェクトには、ストレージシステムの LDAP 構成に関する情報が含まれます。GetLdapConfiguration API メソッドを使用すると、 LDAP 情報を取得できます。 
---
= ldapConfiguration （ ldapConfiguration ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ldapConfiguration オブジェクトには、ストレージシステムの LDAP 構成に関する情報が含まれます。APIメソッドを使用すると、LDAP情報を取得できます `GetLdapConfiguration`。



== オブジェクトメンバー

このオブジェクトのメンバーは次のとおりです。

|===
| 名前 | 製品説明 | タイプ 


 a| 
authType
 a| 
使用するユーザ認証方式を指定します。有効な値：

* DirectBind の場合
* SearchAndBind の場合

 a| 
文字列



 a| 
有効
 a| 
システムが LDAP 用に設定されているかどうかを示します。有効な値：

* 正しい
* 正しくない

 a| 
ブーリアン



 a| 
groupSearchBaseDN
 a| 
グループ検索を開始するツリーのベース DN （ここからサブツリー検索を実行）。
 a| 
文字列



 a| 
groupSearchCustomFilter のように指定します
 a| 
使用するカスタム検索フィルタ。
 a| 
文字列



 a| 
GroupSearchType
 a| 
使用されるデフォルトのグループ検索フィルタを制御します。有効な値：

* NoGroups ：グループのサポートなし。
* ActiveDirectory ：あるユーザの AD グループをすべてネストしたメンバーシップ。
* MemberDN ： MemberDN 形式のグループ（シングルレベル）。

 a| 
文字列



 a| 
searchBindDN
 a| 
ユーザの LDAP 検索を実行するためにログインで使用する完全修飾 DN （ LDAP ディレクトリへの読み取りアクセスが必要）。
 a| 
文字列



 a| 
serverURI
 a| 
LDAPサーバのURIをカンマで区切ったリスト（、など `ldap://1.2.3.4` `ldaps://1.2.3.4:123`）。
 a| 
文字列



 a| 
userDNTemplate
 a| 
完全修飾ユーザ DN を形成するための文字列。
 a| 
文字列



 a| 
userSearchBaseDN のことです
 a| 
検索を開始するツリーのベース DN （ここからサブツリー検索を実行）。
 a| 
文字列



 a| 
userSearchFilter のように入力します
 a| 
使用する LDAP フィルタ。
 a| 
文字列

|===


== 詳細情報

xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration を実行します]
