---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: TestConnectMvip メソッドを使用すると、ストレージクラスタへの管理接続をテストできます。テストでは、 MVIP に対して ping を実行し、シンプルな API メソッドを実行して接続を検証します。 
---
= TestConnectMvip のように入力します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メソッドを使用すると、ストレージクラスタへの管理接続をテストできます `TestConnectMvip`。テストでは、 MVIP に対して ping を実行し、シンプルな API メソッドを実行して接続を検証します。



== パラメータ

このメソッドの入力パラメータは次のとおりです。

|===
| 名前 | 製品説明 | タイプ | デフォルト値 | 必須 


| MVIP | この値を渡して別の MVIP の管理接続をテストすることができます。ターゲットクラスタへの接続をテストするときは、この値を指定する必要はありません。 | 文字列 | なし | いいえ 
|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| 名前 | 製品説明 | タイプ 


| 詳細  a| 
テスト処理に関する情報（ JSON オブジェクト）。

* `connected`：テストでMVIPに接続できたかどうか（ブーリアン）。
* `mvip`：テスト対象のMVIP（文字列）。
* `pingBytes`：pingテストの詳細（56バイトと1、500バイト）（オブジェクト）
+
** `56`：56バイトのpingテストの結果（JSONオブジェクト）：
+
*** `individualResponseTimes`：各アンサンブルノードからの応答時間のリスト（文字列配列）
*** `individualStatus`：各アンサンブルノードからのpingステータスのリスト（ブーリアン配列）。
*** `responseTime`:平均ping応答時間(文字列)
*** `successful`：pingテストが成功したかどうかを示します（ブーリアン）。


** `1500`：1500バイトのpingテストの結果（JSONオブジェクト）：
+
*** `individualResponseTimes`：各アンサンブルノードからの応答時間のリスト（文字列配列）
*** `individualStatus`：各アンサンブルノードからのpingステータスのリスト（ブーリアン配列）。
*** `responseTime`:平均ping応答時間(文字列)
*** `successful`：pingテストが成功したかどうか（ブーリアン）。


** `duration`:テストの実行に必要な時間(文字列)
** `result`:テスト全体の結果(文字列)



| JSON（オブジェクト） 
|===


== 要求例

このメソッドの要求例を次に示します。

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== 応答例

このメソッドの応答例を次に示します。

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== 新規導入バージョン

9.6
